version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: desafio-anota-ai-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-catalog
    volumes:
      - mongodb_data:/data/db
    networks:
      - desafio-network

volumes:
  mongodb_data:

networks:
  desafio-network:
    driver: bridge